version: 0.1
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo "Nothing to build here as it's node!"    
  post_build:
    commands:
      - aws cloudformation package --template-file template.yml 
                                        --s3-bucket simraza-code-bucket1
                                        --output-template-file output.yml
                                        --region ap-southeast-2
artifacts:
  type: s3
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)